### ISSUE TITLE
Got Uncaught TypeError: Relative import path

### ISSUE THREAD

**Issue by kj-1010-1414** [denorg/scrypt#13]
I test in shell, and got this message on import statement:

Uncaught TypeError: Relative import path "std/crypto/timing_safe_equal.ts" not prefixed with / or ./ or ../
    at https://deno.land/x/scrypt@v4.3.0/mod.ts:18:33
    at async <anonymous>:1:47

**Comment by oplik0** [comment]
Note that while it's now fixed in 4.3.1, you can also work around it by adding an import map for `std/` (directly to `deno.json` or via separate json file then referenced via `importMap` in `deno.json` or `--importmap` cli flag):
```json
{
    "imports": {
        "std/": "https://deno.land/std@0.210.0/"
    }
}
```

I just forgot about import maps not being a good idea for libraries without a build step that'd remove them, and the only other place I tested this code also had a `std` import map, so it seemed to work outside of this package too...
